# Docker compose file for netprobe on Unraid
# https://github.com/plaintextpackets/netprobe_lite
#version: '3.8'

networks:
  netprobe-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

services:
  redis:
    restart: always
    container_name: netprobe-redis
    image: redis:latest
    labels:
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/A75G/docker-templates/master/templates/icons/redis.png'
      folder.view: netprobe_lite
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.shell: '/bin/sh'
    volumes:
      - ./config/redis/redis.conf:/etc/redis/redis.conf
    networks:
      netprobe-net:
        ipv4_address: 172.21.0.2
    logging:
      options:
        max-size: "50m"
        max-file: "1"

  netprobe:
    restart: always
    container_name: netprobe-probe
    image: plaintextpackets/netprobe:latest
    volumes:
      - .:/netprobe_lite
    environment:
      - MODULE=NETPROBE
    labels:
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/simonjenny/fastcom-mysql/master/fastlogo.jpg'
      folder.view: netprobe_lite
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.shell: '/bin/sh'
    networks:
      netprobe-net:
        ipv4_address: 172.21.0.3
    logging:
      options:
        max-size: "50m"
        max-file: "1"

  speedtest:
    restart: always
    container_name: netprobe-speedtest
    image: plaintextpackets/netprobe:latest
    labels:
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/speedtest-tracker.png'   
      folder.view: netprobe_lite
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.shell: '/bin/sh'
    volumes:
      - .:/netprobe_lite
    environment:
      - MODULE=SPEEDTEST
    networks:
      netprobe-net:
        ipv4_address: 172.21.0.4
    logging:
      options:
        max-size: "50m"
        max-file: "1"

  presentation:
    restart: always
    container_name: netprobe-presentation
    image: plaintextpackets/netprobe:latest
    volumes:
      - .:/netprobe_lite
    environment:
      - MODULE=PRESENTATION
    labels:
      net.unraid.docker.icon: 'https://github.com/chvb/docker-templates/raw/master/chvb/img/OnlyOfficeDocumentServer.jpg'
      folder.view: netprobe_lite
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.shell: '/bin/sh'
    networks:
      netprobe-net:
        ipv4_address: 172.21.0.5
    logging:
      options:
        max-size: "50m"
        max-file: "1"

  prometheus:
    restart: always
    container_name: netprobe-prometheus
    image: prom/prometheus:latest
    labels:
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/prometheus.png'
      folder.view: netprobe_lite
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.shell: '/bin/sh'
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/data/:/prometheus  # Persistent local storage for Prometheus data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      netprobe-net:
        ipv4_address: 172.21.0.6
    logging:
      options:
        max-size: "50m"
        max-file: "1"

  grafana:
    restart: always
    image: grafana/grafana:main
    labels:
      net.unraid.docker.webui: http://[IP]:[PORT:3000]
      net.unraid.docker.icon: 'https://github.com/atribe/unRAID-docker/raw/master/icons/grafana.png'
      folder.view: netprobe_lite
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.shell: '/bin/sh'
    container_name: netprobe-grafana
    volumes:
      - ./config/grafana/datasources/automatic.yml:/etc/grafana/provisioning/datasources/automatic.yml
      - ./config/grafana/dashboards/main.yml:/etc/grafana/provisioning/dashboards/main.yml
      - ./config/grafana/dashboards/netprobe.json:/var/lib/grafana/dashboards/netprobe.json
      - ./config/grafana/data/:/var/lib/grafana 
      # Persistent local storage for Grafana data
    ports:
      - 3000:3000
    networks:
      netprobe-net:
        ipv4_address: 172.21.0.7
    logging:
      options:
        max-size: "50m"
        max-file: "1"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - USER_ID=99
      - GROUP_ID=100
